### ISSUE TITLE
attempt to concatenate a nil value

### ISSUE THREAD

**Issue by cbaconnier** [NvChad/ui#381]
Hello, 

First of all, thank you for your work on NvChad! 
I'm still a learner, it could be a skill issue.

When I try to use [blade-nav](https://github.com/RicardoRamirezR/blade-nav.nvim) plugin, I'm getting the error when trying to autocomplete: 
> ....local/share/nvim-nvchad/lazy/ui/lua/nvchad/cmp/init.lua:16: attempt to concatenate a nil value

Which correspond to this line: 
https://github.com/NvChad/ui/blob/f2a1b1852e8715fbafcd667855fe8014e024ef03/lua/nvchad/cmp/init.lua#L16

I tried printing `item.kind` and saw something odd:
```
Class                                                                                                             
Class                                                                                                             
Class                                                                                                             
Class                                                                                                             
Interface                                                                                                         
Class                                                                                                             
Interface                                                                                                         
Interface                                                                                                         
Function                                                                                                          
   blade-nav                                                                                                     
   blade-nav  
...
```

I assume this is the relevant part for blade-nav: 
https://github.com/RicardoRamirezR/blade-nav.nvim/blob/ea6b9f36998c9a406849714328c95a0e39c4227d/lua/blade-nav/cmp.lua#L51-L54

As a workaround I manually edited the file lua/nvchad/cmp/init.lua manually to add an early return

```lua
if entry.source.name == "blade-nav" then
  if entry.completion_item.cmp then
    item.kind = entry.completion_item.cmp.kind_text
    item.kind_hl_group = entry.completion_item.cmp.kind_hl_group
    return item
  end
end
```

But I'm not sure what should be done.
Thanks !

**Comment by siduck** [comment]
can you debug it locally? clone the repo locally and use lazy's dir option

![image](https://github.com/user-attachments/assets/0e41d7b8-aad1-4794-a7cd-9dc7fb0be9a9)

then add this, i guess the kind is missing in our icon list

**Comment by cbaconnier** [comment]
Sure!

I cloned the main branch locally, to be sure I was working with the latest version. 

In my understanding, I don't think the list should have this icon. It's more like the author of blade-nav added his own name / icon, (perhaps for convenience ?), and thus fails because this wasn't expected.

I don't know if this is something usual or not.
If this is not something that should normally be done, we can close this issue and I will move it to blade-nav.

This is the result of `vim.print`
![2024-10-23_18-19](https://github.com/user-attachments/assets/64a0f7d3-9923-4c2d-b7a6-801d54739083)

This is what I get when I do the early return
![2024-10-23_18-32](https://github.com/user-attachments/assets/4f929003-9624-4c33-bbf2-656e71569175)

(The early return)
![2024-10-23_18-35](https://github.com/user-attachments/assets/2f1ab774-bc0c-4db1-9896-44e01774ef98)

**Comment by cbaconnier** [comment]
I changed this line (`kind_text`) locally in blade-nav and it works too without any change in NvChad..


https://github.com/RicardoRamirezR/blade-nav.nvim/blob/ea6b9f36998c9a406849714328c95a0e39c4227d/lua/blade-nav/cmp.lua#L53

 ```lua
cmp = {
  kind_hl_group = "CmpItemKindBladeNav",
  --kind_text = "  " .. " blade-nav",
  kind_text = "Field",
},
 ```
![2024-10-23_19-34](https://github.com/user-attachments/assets/097f4b72-f59a-406c-b1aa-1f715c758768)

So this confirm what I understood. But I still don't know if this is something to be changed in blade-nav or NvChad/ui

**Comment by siduck** [comment]
i added `field` as fallback icon for cmp, do lazy sync. should be fixed

**Comment by cbaconnier** [comment]
Thanks! Really appreciated
I still have the issue though. Since the `kind` is filled but not with a known icon.
I will suggest a PR, I have a better understanding of what happens now.

**Comment by siduck** [comment]
> in blade-nav or

it shouldnt, i set the field kind as fallback

**Comment by cbaconnier** [comment]
Here's a deep down of what happens;

![2024-10-24_11-29](https://github.com/user-attachments/assets/246259c6-528c-4cf1-a694-a61372c752eb)

From my understanding, the fallback only works when `item.kind` is not set. 
I think if `item.kind`is not present in `icons`, it should just return the item as it is and let cmp deal with what it receive (see #382)

**Comment by siduck** [comment]
@cbaconnier  can you add these 2 lines 

![image](https://github.com/user-attachments/assets/eeffc41d-3c41-4bda-ac38-a5347036dd05)


```lua
      local icon = icons[item.kind] or icons.field
      item.kind = (cmp_ui.icons_left and icon or " " .. icon) .. "  "
```

**Comment by cbaconnier** [comment]
I'm getting  `attempt to index local 'icon' (a nil value)`
At this line : `item.kind = (cmp_ui.icons_left and icon or " " .. icon.kind) .. "  "`

Beside, the current `item.kind` (`   blade-nav`) also causes an issue to `menu_hl_group` because it contains _an invalid character_.

**Comment by siduck** [comment]
hmmm, can we talk on discord etc? so i'll get this resolved quick & rather than opening github everytime for notifs! join the nvchad server

**Comment by siduck** [comment]
https://github.com/NvChad/ui/commit/cfafe4aeb7b5d7ffde097d3d8df61289e33a6d51
